export const data = JSON.parse("{\"key\":\"v-3c3196fe\",\"path\":\"/quests/lvl1-10.html\",\"title\":\"Level 1~10\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"King's Recruit(level 1) 国王的招兵 :::tip 此任务为新手教程，可用/skiptutorial跳过至最后步骤 ::: 1.在马车撞到石头后，下车，和[-1573 51 -1626]的大篷车司机对话。通过按下潜行键(默认为shift)来继续对话。 2.对话结束后，带领Tasim沿着道路往前走，直到和大门前的Aledar自动触发...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/WynncraftCNguide/quests/lvl1-10.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Wynncraft中文攻略\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Level 1~10\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"King's Recruit(level 1) 国王的招兵 :::tip 此任务为新手教程，可用/skiptutorial跳过至最后步骤 ::: 1.在马车撞到石头后，下车，和[-1573 51 -1626]的大篷车司机对话。通过按下潜行键(默认为shift)来继续对话。 2.对话结束后，带领Tasim沿着道路往前走，直到和大门前的Aledar自动触发...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Level 1~10\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"King's Recruit(level 1)\",\"slug\":\"king-s-recruit-level-1\",\"link\":\"#king-s-recruit-level-1\",\"children\":[]},{\"level\":2,\"title\":\"Poisoning the Pest(level 2)\",\"slug\":\"poisoning-the-pest-level-2\",\"link\":\"#poisoning-the-pest-level-2\",\"children\":[]},{\"level\":2,\"title\":\"Cook Assistant(level 3)\",\"slug\":\"cook-assistant-level-3\",\"link\":\"#cook-assistant-level-3\",\"children\":[]},{\"level\":2,\"title\":\"Infested Plants ( level 4 )\",\"slug\":\"infested-plants-level-4\",\"link\":\"#infested-plants-level-4\",\"children\":[]},{\"level\":2,\"title\":\"Sewers of Ragni( level 5 )\",\"slug\":\"sewers-of-ragni-level-5\",\"link\":\"#sewers-of-ragni-level-5\",\"children\":[]},{\"level\":2,\"title\":\"Mushroom Man ( level 6 )\",\"slug\":\"mushroom-man-level-6\",\"link\":\"#mushroom-man-level-6\",\"children\":[]},{\"level\":2,\"title\":\"Tunnel Trouble ( level 6 )\",\"slug\":\"tunnel-trouble-level-6\",\"link\":\"#tunnel-trouble-level-6\",\"children\":[]},{\"level\":2,\"title\":\"Taking the tower ( level 8 )\",\"slug\":\"taking-the-tower-level-8\",\"link\":\"#taking-the-tower-level-8\",\"children\":[]},{\"level\":2,\"title\":\"Underwater ( level 8 )\",\"slug\":\"underwater-level-8\",\"link\":\"#underwater-level-8\",\"children\":[]},{\"level\":2,\"title\":\"Maltic's Well ( level 10)\",\"slug\":\"maltic-s-well-level-10\",\"link\":\"#maltic-s-well-level-10\",\"children\":[]}],\"readingTime\":{\"minutes\":7.93,\"words\":2378},\"filePathRelative\":\"quests/lvl1-10.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
