export const data = JSON.parse("{\"key\":\"v-e82d1030\",\"path\":\"/guide/VIP.html\",\"title\":\"氪金项目\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"氪金项目\",\"icon\":\"gem\",\"description\":\":::warning 不提倡氪金 ::: 你可以通过访问线上商店来查看所有氪金项目 购买前只需输入用户名即可，无需另外注册 支持支付宝。 Ranks 相当于VIP 一共有四个等级：VIP、`VIP+、HERO、CHAMPION :::details rank的主要功能 更高级的rank均包含低级rank的所有内容 如果你已经拥有了低级rank，则升级高...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/EternityTQ/WynncraftCNguide/guide/VIP.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Wynncraft中文攻略\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"氪金项目\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\":::warning 不提倡氪金 ::: 你可以通过访问线上商店来查看所有氪金项目 购买前只需输入用户名即可，无需另外注册 支持支付宝。 Ranks 相当于VIP 一共有四个等级：VIP、`VIP+、HERO、CHAMPION :::details rank的主要功能 更高级的rank均包含低级rank的所有内容 如果你已经拥有了低级rank，则升级高...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"氪金项目\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Ranks\",\"slug\":\"ranks\",\"link\":\"#ranks\",\"children\":[{\"level\":3,\"title\":\"Mob Totem\",\"slug\":\"mob-totem\",\"link\":\"#mob-totem\",\"children\":[]},{\"level\":3,\"title\":\"皮肤职业\",\"slug\":\"皮肤职业\",\"link\":\"#皮肤职业\",\"children\":[]},{\"level\":3,\"title\":\"每日饰品箱\",\"slug\":\"每日饰品箱\",\"link\":\"#每日饰品箱\",\"children\":[]},{\"level\":3,\"title\":\"炸弹钟\",\"slug\":\"炸弹钟\",\"link\":\"#炸弹钟\",\"children\":[]}]},{\"level\":2,\"title\":\"SliverBull & Share\",\"slug\":\"sliverbull-share\",\"link\":\"#sliverbull-share\",\"children\":[{\"level\":3,\"title\":\"Silverbull Shop\",\"slug\":\"silverbull-shop\",\"link\":\"#silverbull-shop\",\"children\":[]}]},{\"level\":2,\"title\":\"Crates\",\"slug\":\"crates\",\"link\":\"#crates\",\"children\":[{\"level\":3,\"title\":\"Scrap Rewards\",\"slug\":\"scrap-rewards\",\"link\":\"#scrap-rewards\",\"children\":[]},{\"level\":3,\"title\":\"节日Crates\",\"slug\":\"节日crates\",\"link\":\"#节日crates\",\"children\":[]}]},{\"level\":2,\"title\":\"Pets\",\"slug\":\"pets\",\"link\":\"#pets\",\"children\":[]},{\"level\":2,\"title\":\"Bombs\",\"slug\":\"bombs\",\"link\":\"#bombs\",\"children\":[]}],\"readingTime\":{\"minutes\":9.98,\"words\":2994},\"filePathRelative\":\"guide/VIP.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
