export const data = JSON.parse("{\"key\":\"v-4b7bf771\",\"path\":\"/guide/basesystem/command.html\",\"title\":\"常用命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"常用命令\",\"icon\":\"code\",\"description\":\"这一篇主要是讲述游戏内经常会用到的、实用的命令 /class 切换至选角界面 但是其功能不止这么简单，还有一系列的附加功能：\\r使用后会清除身上所有正面、负面效果; \\r由于使用后原地点周围没有玩家，可用此命令来重置机关、重刷新怪物; 总之就是遇到BUG的时候先试试/class，说不定有很大作用 /kill 自杀。 自杀后会自动复活在临近的等级足够的城镇 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/EternityTQ/WynncraftCNguide/guide/basesystem/command.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Wynncraft中文攻略\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"常用命令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"这一篇主要是讲述游戏内经常会用到的、实用的命令 /class 切换至选角界面 但是其功能不止这么简单，还有一系列的附加功能：\\r使用后会清除身上所有正面、负面效果; \\r由于使用后原地点周围没有玩家，可用此命令来重置机关、重刷新怪物; 总之就是遇到BUG的时候先试试/class，说不定有很大作用 /kill 自杀。 自杀后会自动复活在临近的等级足够的城镇 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"常用命令\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"/class\",\"slug\":\"class\",\"link\":\"#class\",\"children\":[]},{\"level\":2,\"title\":\"/kill\",\"slug\":\"kill\",\"link\":\"#kill\",\"children\":[]},{\"level\":2,\"title\":\"/pfinder\",\"slug\":\"pfinder\",\"link\":\"#pfinder\",\"children\":[]},{\"level\":2,\"title\":\"/find\",\"slug\":\"find\",\"link\":\"#find\",\"children\":[]},{\"level\":2,\"title\":\"/fixquests\",\"slug\":\"fixquests\",\"link\":\"#fixquests\",\"children\":[]},{\"level\":2,\"title\":\"/report\",\"slug\":\"report\",\"link\":\"#report\",\"children\":[]},{\"level\":2,\"title\":\"/itemlock\",\"slug\":\"itemlock\",\"link\":\"#itemlock\",\"children\":[]},{\"level\":2,\"title\":\"/stream\",\"slug\":\"stream\",\"link\":\"#stream\",\"children\":[]},{\"level\":2,\"title\":\"/use\",\"slug\":\"use\",\"link\":\"#use\",\"children\":[]},{\"level\":2,\"title\":\"/claimitembomb\",\"slug\":\"claimitembomb\",\"link\":\"#claimitembomb\",\"children\":[]},{\"level\":2,\"title\":\"/daily\",\"slug\":\"daily\",\"link\":\"#daily\",\"children\":[]},{\"level\":2,\"title\":\"/pq\",\"slug\":\"pq\",\"link\":\"#pq\",\"children\":[]},{\"level\":2,\"title\":\"/changetag\",\"slug\":\"changetag\",\"link\":\"#changetag\",\"children\":[]},{\"level\":2,\"title\":\"/switch\",\"slug\":\"switch\",\"link\":\"#switch\",\"children\":[]},{\"level\":2,\"title\":\"/totems\",\"slug\":\"totems\",\"link\":\"#totems\",\"children\":[]},{\"level\":2,\"title\":\"/toggle\",\"slug\":\"toggle\",\"link\":\"#toggle\",\"children\":[]}],\"readingTime\":{\"minutes\":3.83,\"words\":1149},\"filePathRelative\":\"guide/basesystem/command.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
