export const data = JSON.parse("{\"key\":\"v-1cba378b\",\"path\":\"/guide/raid/tna.html\",\"title\":\"The Nameless Anomaly\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"The Nameless Anomaly\",\"icon\":\"ghost\",\"description\":\"无名异常 名称：The Nameless Anomaly 简称：TNA 玩家等级限制：103 团队总等级上限：500 团队人数限制：4 入场费用：5 Tol Runes 前置任务：A Journey Further (level 101) (/quests/lvl101-110/level%20101%20-%20A%20Journey%20Furth...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/EternityTQ/WynncraftCNguide/guide/raid/tna.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Wynncraft中文攻略\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"The Nameless Anomaly\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"无名异常 名称：The Nameless Anomaly 简称：TNA 玩家等级限制：103 团队总等级上限：500 团队人数限制：4 入场费用：5 Tol Runes 前置任务：A Journey Further (level 101) (/quests/lvl101-110/level%20101%20-%20A%20Journey%20Furth...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"The Nameless Anomaly\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Room1\",\"slug\":\"room1\",\"link\":\"#room1\",\"children\":[{\"level\":3,\"title\":\"Flooding Canyon - 虚空洞\",\"slug\":\"flooding-canyon-虚空洞\",\"link\":\"#flooding-canyon-虚空洞\",\"children\":[]},{\"level\":3,\"title\":\"Sunken Grotto - 平台\",\"slug\":\"sunken-grotto-平台\",\"link\":\"#sunken-grotto-平台\",\"children\":[]}]},{\"level\":2,\"title\":\"Room2\",\"slug\":\"room2\",\"link\":\"#room2\",\"children\":[{\"level\":3,\"title\":\"Weeping Soulroot - 树\",\"slug\":\"weeping-soulroot-树\",\"link\":\"#weeping-soulroot-树\",\"children\":[]},{\"level\":3,\"title\":\"Nameless Cave - Light\",\"slug\":\"nameless-cave-light\",\"link\":\"#nameless-cave-light\",\"children\":[]}]},{\"level\":2,\"title\":\"Room3\",\"slug\":\"room3\",\"link\":\"#room3\",\"children\":[{\"level\":3,\"title\":\"bulbshift Wilds - 灯泡\",\"slug\":\"bulbshift-wilds-灯泡\",\"link\":\"#bulbshift-wilds-灯泡\",\"children\":[]},{\"level\":3,\"title\":\"Twisted Jungle - 传送门\",\"slug\":\"twisted-jungle-传送门\",\"link\":\"#twisted-jungle-传送门\",\"children\":[]}]},{\"level\":2,\"title\":\"Boss\",\"slug\":\"boss\",\"link\":\"#boss\",\"children\":[]},{\"level\":2,\"title\":\"buff\",\"slug\":\"buff\",\"link\":\"#buff\",\"children\":[]},{\"level\":2,\"title\":\"Reward\",\"slug\":\"reward\",\"link\":\"#reward\",\"children\":[]}],\"readingTime\":{\"minutes\":12.79,\"words\":3837},\"filePathRelative\":\"guide/raid/tna.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
