<template>
  <div class="wynn-tree-wrapper">
    <div class="tree-scroll-container">
      
      <div class="tree-content" :style="containerStyle">
        
        <svg class="connections-layer">
          <path 
            v-for="(pathD, index) in connectorPaths" 
            :key="index"
            :d="pathD" 
            class="connector-line"
          />
        </svg>

        <div class="skill-grid" :style="gridStyle">
          <SkillNode 
            v-for="(item, index) in combinedItems" 
            :key="`item-${index}`" 
            :name="item.display_name"
            :current-class="currentClass" 
            :style="getItemStyle(item)"
          />
        </div>
      
      </div>
    </div>
  </div>
</template>

<script>
import SkillNode from './SkillNode.vue'; 
import atreeData from './data/atree.json'; 
import connectorData from './data/connectors.json'; 

export default {
  components: { SkillNode },
  props: {
    // 【修改】通过 Props 接收职业，不再自己管理
    currentClass: {
      type: String,
      default: 'Archer'
    }
  },
  data() {
    return {
      // ...
      // 【修改】这里控制整体大小！
      // 如果想撑满，可以改大到 60 或 65
      // 如果想保持紧凑但去除留白，请看下面的 CSS 修改
      gridCellSize: 60, 
      gridGap: 0,       
    };
  },
  computed: {
    // 1. 获取原始技能数据
    rawSkills() {
      return atreeData[this.currentClass] || [];
    },

    skills() {
      // 仅仅做深拷贝，防止污染源数据，不再修改 row
      return this.rawSkills.map(skill => JSON.parse(JSON.stringify(skill)));
    },

    // 2. 自动生成连接线数据
    autoGeneratedConnectors() {
      const connectionMap = new Map(); // key: "row,col", value: {up, down, left, right}

      // 遍历所有技能节点
      this.skills.forEach(skill => {
        const childRow = skill.display.row;
        const childCol = skill.display.col;

        // 处理每个父节点
        if (skill.parents && skill.parents.length > 0) {
          skill.parents.forEach(parentId => {
            const parent = this.skills.find(s => s.id === parentId);
            if (!parent) return;

            const parentRow = parent.display.row;
            const parentCol = parent.display.col;

            // 如果父子节点相邻（row差1）且在同一列，直接连接，无需连接符
            if (childRow === parentRow + 1 && childCol === parentCol) {
              return;
            }

            // 路径策略：从子节点向上移动，遇到需要水平移动的位置后水平移动到父节点列，然后继续向上
            // 水平移动发生在父节点所在行

            const minCol = Math.min(parentCol, childCol);
            const maxCol = Math.max(parentCol, childCol);

            // 步骤1：垂直连接 - 从子节点上方到父节点行+1（不包括父节点行）
            for (let r = childRow - 1; r > parentRow; r--) {
              this.addConnection(connectionMap, r, childCol, 'up', 'down');
            }

            // 步骤2：在父节点行上进行水平连接（如果需要）
            if (parentCol !== childCol) {
              // 需要水平移动
              for (let c = minCol + 1; c < maxCol; c++) {
                // 水平线段：中间所有格子都是左右连接（排除父节点和子节点位置）
                this.addConnection(connectionMap, parentRow, c, 'left', 'right');
              }

              // 拐角处理
              if (childRow > parentRow + 1) {
                // 有垂直段 + 水平段，需要拐角
                // 拐角在 (parentRow, childCol) 位置，但要确保不是节点位置
                if (parentCol < childCol) {
                  // 父在左，子在右：在 (parentRow, childCol) 产生"左下"拐角
                  this.addConnection(connectionMap, parentRow, childCol, 'down', 'left');
                } else {
                  // 父在右，子在左：在 (parentRow, childCol) 产生"右下"拐角
                  this.addConnection(connectionMap, parentRow, childCol, 'down', 'right');
                }
              } else {
                // 父子相邻行，只有水平移动
                // 在子节点正上方 (parentRow, childCol) 需要水平和向下的连接
                // 但这个位置就是 parentRow，所以不会和子节点冲突
                if (parentCol < childCol) {
                  this.addConnection(connectionMap, parentRow, childCol, 'left', 'down');
                } else {
                  this.addConnection(connectionMap, parentRow, childCol, 'right', 'down');
                }
              }

              // 父节点位置的连接会被过滤掉，所以这里标记是安全的
              if (parentCol === minCol) {
                this.addConnection(connectionMap, parentRow, parentCol, 'down', 'right');
              } else {
                this.addConnection(connectionMap, parentRow, parentCol, 'down', 'left');
              }
            } else {
              // 父子同列，只需垂直连接
              // 父节点位置的连接会被过滤掉
              if (childRow > parentRow + 1) {
                this.addConnection(connectionMap, parentRow, parentCol, 'down', 'up');
              }
            }
          });
        }
      });

      // 将 connectionMap 转换为连接符数组
      return this.convertConnectionMapToConnectors(connectionMap);
    },

    // 3. 处理连线数据：可以选择使用手动数据或自动生成数据
    connectorItems() {
      // 使用自动生成的连接线
      return this.autoGeneratedConnectors;

      // 如果想使用手动数据，可以注释上面一行，取消注释下面的代码：
      /*
      const classConnectors = connectorData[this.currentClass];
      if (!classConnectors) return [];

      const items = [];

      for (const [type, coords] of Object.entries(classConnectors)) {
        if (Array.isArray(coords)) {
          coords.forEach(pos => {
            items.push({
              display_name: type,
              display: {
                row: pos.row,
                col: pos.col,
                icon: type
              }
            });
          });
        }
      }
      return items;
      */
    },

    // 4. 合并数据：技能 + 连线
    combinedItems() {
      return [...this.skills, ...this.connectorItems];
    },

    // 5. 计算网格最大尺寸
    gridDimensions() {
      let maxRow = 0;
      this.combinedItems.forEach(item => {
        if (item.display.row > maxRow) maxRow = item.display.row;
      });
      // 【修改】这里改为 +3，给底部留出更多富余空间，防止图标边缘被切
      return { rows: maxRow + 3, cols: 9 };
    },

    containerStyle() {
      const width = this.gridDimensions.cols * (this.gridCellSize + this.gridGap);
      const height = this.gridDimensions.rows * (this.gridCellSize + this.gridGap);
      return { width: `${width}px`, height: `${height}px` };
    },

    gridStyle() {
      return {
        'grid-template-columns': `repeat(${this.gridDimensions.cols}, ${this.gridCellSize}px)`,
        'grid-template-rows': `repeat(${this.gridDimensions.rows}, ${this.gridCellSize}px)`,
        'gap': `${this.gridGap}px`,
        'width': '100%',
        'height': '100%'
      };
    }
  },
  methods: {
    getItemStyle(item) {
      return {
        gridRow: item.display.row + 1,
        gridColumn: item.display.col + 1
      };
    },

    // 辅助方法：向 connectionMap 添加连接
    addConnection(connectionMap, row, col, ...directions) {
      const key = `${row},${col}`;
      if (!connectionMap.has(key)) {
        connectionMap.set(key, { up: false, down: false, left: false, right: false });
      }
      const conn = connectionMap.get(key);
      directions.forEach(dir => {
        if (dir) conn[dir] = true;
      });
    },

    // 辅助方法：将 connectionMap 转换为连接符数组
    convertConnectionMapToConnectors(connectionMap) {
      const items = [];

      // 创建技能节点位置的集合，用于检查冲突
      const skillPositions = new Set();
      this.skills.forEach(skill => {
        const key = `${skill.display.row},${skill.display.col}`;
        skillPositions.add(key);
      });

      connectionMap.forEach((directions, key) => {
        const [row, col] = key.split(',').map(Number);

        // 如果这个位置已经有技能节点，跳过不生成连接符
        if (skillPositions.has(key)) {
          // 调试日志：显示哪些位置被跳过
          // console.log(`跳过节点位置: row=${row}, col=${col}`);
          return;
        }

        const { up, down, left, right } = directions;

        // 根据四个方向的连接情况决定连接符类型
        let connectorType = null;

        // 统计连接方向数量
        const connectionCount = [up, down, left, right].filter(Boolean).length;

        if (connectionCount === 0) {
          return; // 没有连接，跳过
        } else if (connectionCount === 1) {
          // 单向连接不需要连接符（通常是端点）
          return;
        } else if (connectionCount === 2) {
          // 两个方向
          if (up && down) {
            connectorType = '竖线';
          } else if (left && right) {
            connectorType = '横线';
          } else if (down && right) {
            connectorType = '右下'; // 右下拐角
          } else if (down && left) {
            connectorType = '左下'; // 左下拐角
          } else if (up && right) {
            // 暂时用右下代替（可能需要添加对应图片）
            connectorType = '右下';
          } else if (up && left) {
            // 暂时用左下代替（可能需要添加对应图片）
            connectorType = '左下';
          }
        } else if (connectionCount === 3) {
          // 三个方向：丁字类型
          if (!up) {
            connectorType = '丁字'; // 左下右（没有上）
          } else if (!left) {
            connectorType = '右丁字'; // 上右下（没有左）
          } else if (!right) {
            connectorType = '左丁字'; // 上左下（没有右）
          } else if (!down) {
            // 上左右（没有下）：暂时使用丁字
            connectorType = '丁字';
          }
        } else if (connectionCount === 4) {
          // 四个方向都有
          connectorType = '十字';
        }

        if (connectorType) {
          items.push({
            display_name: connectorType,
            display: {
              row: row,
              col: col,
              icon: connectorType
            }
          });
        }
      });

      return items;
    }
  }
}
</script>

<style scoped>
.wynn-tree-wrapper {
  /* 【修改】原来是 width: 100%; 改为 fit-content */
  width: fit-content; 
  /* 或者使用 inline-block */
  /* display: inline-block; */
  
  min-width: 100%; /* 选填：如果你希望它至少占满一行，但内容少时不要留白，这就比较矛盾。通常用 fit-content 配合居中即可 */
  
  height: 800px;
  background-color: #292929;
  border: 1px solid #333;
  overflow: hidden; 
  position: relative;
  
  /* 如果改为 fit-content 后想让整个表格在页面居中，可以加这个： */
  margin: 0 auto; 
}

.tree-scroll-container {
  width: 100%;
  height: 100%;
  overflow: auto;
  /* 【修改】上下保留 20px 缓冲，左右设为 0 以消除"多余列"的视觉感 */
  padding: 20px 0; 
  display: flex;
  justify-content: center; /* 保持居中，或者改为 flex-start 靠左对齐 */
}

.tree-content {
  position: relative; 
}

.skill-grid {
  display: grid;
  position: relative;
  /* 强力消除间隙方案 A */
  font-size: 0; 
  line-height: 0;
}

::v-deep .skill-container {
  margin: 0;
  padding: 0;
  border: none;
  outline: none;
  display: block; /* 改为 block 试试，或者 flex */
}

::v-deep .skill-icon {
  display: block; /* 必须是 block */
  width: 100%;
  height: 100%;
  /* 强力消除间隙方案 B: 稍微放大一点点覆盖缝隙 (如果上面不管用) */
  /* transform: scale(1.02); */ 
}
</style>